### ISSUE TITLE
`python.app` version should match `python` version

### ISSUE THREAD

**Issue by hoechenberger** [conda-forge/python.app-feedstock#8] opened 2020-03-06 12:49 UTC
Issue:
We keep running into issues on macOS with multiprocessing because the Python versions in `python.app` and `python` don't match. This causes segfaults in multiprocessing pools at least for the current `python`/`python.app` combination for Python 3.7 on `conda-forge`.

Example for `python[.app]` with Python 3.7:
```
$ python --version
Python 3.7.6
$ python.app --version
Python 3.7.3
```

@cbrnr had reported this issue to the Anaconda issue tracker, and it has since been fixed in `defaults`: https://github.com/ContinuumIO/anaconda-issues/issues/11633

**Comment by hoechenberger** [comment] 2020-03-06 21:01
Looking at the recipe and build script, my understanding is that we simply need to bump the build number of the `python.app` package every time a new `python` package has been built. This will keep the Python versions in both packages in sync. I believe that, ideally, `python.app` and `python` should probably be merged into a single package, with `python.app` obviously only built and deployed for macOS.

**Comment by ChrisBarker-NOAA** [comment] 2020-03-06 21:11
hmm -- it seems that that might work. But it also seems like a kludge.

Maybe Python.app should have a version that matches python? And/or set a pinned dependency so that, for example version x.y of Python.app would depend on a particular version of Python.

Not sure quite how to do that now, though, what with python 2 and 3 -- though since python2 is not going to be moving forward, maybe we just build a python.app 2.7.17, and then move on.

**Comment by hoechenberger** [comment] 2020-03-06 21:14
Hello @ChrisBarker-NOAA, thanks for your response. I'm not sure how pinning would work in this case – are you thinking of specifying an exact Python version, as in, `python=1.2.3`? We would have to create 3 branches then -- one for Py2.7, one for 3.6, one for 3.7, while 3.8 for the time being can live in `master`. WDYT?

**Comment by ChrisBarker-NOAA** [comment] 2020-03-06 21:29
well, it would be a pain to get it set up for all supported versions, but then would just be a version bump with each new Python. I *think* we could use branches for that, but not too sure exactly how.

It would take a conda-forge core member with a better understanding than me to decide if it makes sense.

In the meantime, let's try the build number bump, once we've fixed the LICENSE issue.

**Comment by hoechenberger** [comment] 2020-03-06 21:34
> I _think_ we could use branches for that, but not too sure exactly how.

I've done that before, for example for `pyglet` I needed a build of the latest patch release of version 1.3, although the feedstock had already moved on to 1.4. So we created a new branch that holds 1.3. See the branches here: https://github.com/conda-forge/pyglet-feedstock/branches

> In the meantime, let's try the build number bump, once we've fixed the LICENSE issue.

What's the deal with that, anyway? Which license file do we need to include? Should we simply drop a copy of the [BSD license from the `python` feedstock](https://github.com/conda-forge/python-feedstock/blob/d127e33ec1c1332642ea810cdc1d09ea61add425/recipe/LICENSE.txt) here?

**Comment by ChrisBarker-NOAA** [comment] 2020-03-06 21:38
it's already there -- you just need to point the meta.yaml file to it.

**Comment by hoechenberger** [comment] 2020-03-06 21:40
> it's already there -- you just need to point the meta.yaml file to it.

No it's not :) See https://github.com/conda-forge/python.app-feedstock/pull/9#issuecomment-595976433

**Comment by ChrisBarker-NOAA** [comment] 2020-03-06 21:42
isn't this it?

https://github.com/conda-forge/python.app-feedstock/blob/master/LICENSE.txt

**Comment by hoechenberger** [comment] 2020-03-06 21:43
No that's not it. That's the license file of this _feedstock_, not the license file of the thing being packaged, which should be placed in `recipes/`.

**Comment by ChrisBarker-NOAA** [comment] 2020-03-06 21:48
This is an unusual case, as far as I can tell, the recipe IS the code -- it's not getting it from elsewhere.

So presumably it has the same license.

But if conda-build needs it in the recipe, then might as well make a copy of in the recipe.

By the way, would you like to add yourself to the maintainers list?

**Comment by ChrisBarker-NOAA** [comment] 2020-03-06 22:03
Status:

We've bumped the build number to trigger a rebuild, but I suspect that may end up breaking other versions of Python.

So it seems we really should have the Python.app package released with a version number that matches Python, and be pinned to exactly that version of Python.

Which would take a bit of work to setup, but then once the current versions were all built, it would be pretty straightforward to keep it up with new releases.

**Comment by hoechenberger** [comment] 2020-03-06 22:06
> but I suspect that may end up breaking other versions of Python.

How so?

> Which would take a bit of work to setup

I really don't think it's going to be difficult, we simply create multiple branches, one for each Python minor release. I can do that tomorrow :)

**Comment by ChrisBarker-NOAA** [comment] 2020-03-06 22:08
BTW, it's out of sync for 3.8 as well:

(py3) ORR-M-4420442:~ chris.barker$ python --version
Python 3.8.2
(py3) ORR-M-4420442:~ chris.barker$ python.app --version
Python 3.8.0

we'll see if the build bump takes care of this.

**Comment by hoechenberger** [comment] 2020-03-06 22:09
> BTW, it's out of sync for 3.8 as well:

Yes. It's out of sync for all versions. But we only ran into segfaults on 3.7 due to this issue – pure luck I guess :)



> we'll see if the build bump takes care of this.

👍

**Comment by ChrisBarker-NOAA** [comment] 2020-03-06 22:31
The bump has triggered the builds, and they are up on anaconda.org.

However, I can't seem to get conda to update it :-( whether I update or remove and install, it still find an older build.

downloading and installing the package directly works though.

**Comment by cbrnr** [comment] 2020-03-06 22:34
I assume including a symlink to python isn't supported by conda?

**Comment by hoechenberger** [comment] 2020-03-06 22:42
> However, I can't seem to get conda to update it :-( whether I update or remove and install, it still find an older build.

It often takes up to an hour until your conda "finds" the new packages, as they need to be distributed to different mirrors first.

**Comment by ChrisBarker-NOAA** [comment] 2020-03-06 22:43
We're getting a bit out of my area of expertise, but the whole Python.app thing is to satisfy an Apple requirement that the executable itself be Inside an App bundle. So I don't think a Symlink inside an app bundle would work.

I am wondering if there is a way to for conda to make a copy or hardlink at install time, but then if you updated Python, Python.app would need to be reinstalled.

**Comment by hoechenberger** [comment] 2020-03-06 22:44
@cbrnr 

> I assume including a symlink to python isn't supported by conda?

they are supported, but where should they point to? At build time, we wouldn't know the name of the environment the user is going to install `python.app` into. Do you think a relative symlink could solve the issue?

**Comment by ChrisBarker-NOAA** [comment] 2020-03-06 22:44
NOTE: I've posted a note to the conda-forge list about this, if anyone wants to join:

https://groups.google.com/forum/#!topic/conda-forge/vrjPKL6AJUA

**Comment by hoechenberger** [comment] 2020-03-06 22:45
> I am wondering if there is a way to for conda to make a copy or hardlink at install time, but then if you updated Python, Python.app would need to be reinstalled.

I'd actually prefer the `python.app` package be abandoned and its functionality merged into the `python` package. That way, they would always stay in sync.

**Comment by ChrisBarker-NOAA** [comment] 2020-03-06 22:58
Well, yes, that would probably be the "right" way to go.

I don't see any downside to Python.app always getting shipped with Python on OS-X.

NOTE: even better would be for the OS-X Python build to use the python.org "hack" to get a pythonw that works everywhere.

See: https://github.com/conda-forge/python-feedstock/issues/23#issuecomment-228473432

As far as I can tell, it "just" needs someone to do the painful work with autoconf  to try it out.

**Comment by hoechenberger** [comment] 2020-03-06 23:01
> NOTE: even better would be for the OS-X Python build to use the python.org "hack" to get a pythonw that works everywhere.
> 
> See: [conda-forge/python-feedstock#23 (comment)](https://github.com/conda-forge/python-feedstock/issues/23#issuecomment-228473432)
> 
> As far as I can tell, it "just" needs someone to do the painful work with autoconf to try it out.

Yes, @cbrnr and I (and probably sooo many others) would _love_ to see this happen. Special handling for conda Python in GUI apps is such a pain. FWIW Python.org's builds don't _need_ a `pythonw` thingy anymore.

**Comment by hoechenberger** [comment] 2020-03-07 06:42
There's been a request in the past to add `python.app` as a build output to the `python` feedstock, because people ran into issues when installing `conda-forge` `python.app` with `defaults` `python`.

https://github.com/conda-forge/python-feedstock/issues/230

So this is another argument to drop this feedstock and to have everything in one place, namely the `python` feedstock.

**Comment by cbrnr** [comment] 2020-03-07 07:51
Symlinking to `python` solves the problem. Because the locations are known a relative symlink would actually work!

**Comment by hoechenberger** [comment] 2020-03-07 09:08
I like this idea. Using a symlink would allow us to use only _one_ recipe for _all_ Python versions, instead of having to create a separate branch for each Python minor release. And maintenance would also be largely simplified as we wouldn't have to rebuild when a new `python` package is released. I will try to look into this.

**Comment by ChrisBarker-NOAA** [comment] 2020-03-07 22:47
HAs this been tested, and works?

I'm pretty sure a symlink will not work -- the actual executable has to be inside the bundle.

But I'd love to know I'm wrong.

It could be done as a hard link during the install, but then if you updated python, they'd be out of sync again.

If this doesn't work, then I see two options:

1) preferred: simply have python.app we built and shipped as part of python on OS-X -- I can't really see a downside here, except that folks will get a small amount of unneeded extra stuff. Is there any other reason not to do it??

2) pin the version numbers of python.app to python -- kind of a pain, but once set up, not too hard to maintain.

**Comment by hoechenberger** [comment] 2020-03-07 23:27
> HAs this been tested, and works?
> 
> I'm pretty sure a symlink will not work -- the actual executable has to be inside the bundle.
> 
> But I'd love to know I'm wrong.

It does work, see the test script added to #11 which checks it works correctly:
https://github.com/conda-forge/python.app-feedstock/blob/cd590a86bc9bfed279727a3c7bd58b9550470a7c/recipe/run_test.sh

Also @cbrnr did some successful testing with symlinks.



> * preferred: simply have python.app we built and shipped as part of python on OS-X -- I can't really see a downside here, except that folks will get a small amount of unneeded extra stuff. Is there any other reason not to do it??

I would say we should merge #11 first and then take the code from this feedstock and extend `python-feedstock` accordingly to build `python.app` as part of `python`, yes. See https://github.com/conda-forge/python-feedstock/issues/230#issuecomment-596054178
But this would require significantly more work than simply adding a symlink in `python.app-feedstock`.

**Comment by ChrisBarker-NOAA** [comment] 2020-03-07 23:56
I'm afraid that doesn't test if Python.app works as intended.

We need to try running a GUI app with it, with the symlink in place instead of a copy.

I'd be glad to be proven wrong, but there is a reason is was done this way in the first place.

I'll give that a try now.

**Comment by ChrisBarker-NOAA** [comment] 2020-03-08 00:36
So I've done a symlnk hack into my existing install, and indeed, it seems to work, at least with wxPython.

I am pleasantly surprised

So this may be a solution. Thanks!

**Closed as completed** 2020-03-10 15:39 UTC
